# Generated by Django 2.0.5 on 2018-07-09 22:29

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(choices=[(0, 'Perdido'), (1, 'Disponible'), (2, 'En Préstamo'), (3, 'Perdido o Inutilizable')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(choices=[(0, 'Perdido'), (1, 'Disponible'), (2, 'En Préstamo'), (3, 'Perdido o Inutilizable')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FotoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, upload_to='')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEspacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, upload_to='')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(default=0)),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_inicial', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('fecha_final', models.DateField()),
                ('hora_final', models.TimeField()),
                ('estado', models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_inicial', models.DateField()),
                ('hora_inicial', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(9)])),
                ('fecha_final', models.DateField()),
                ('hora_final', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(10)])),
                ('estado', models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
