# Generated by Django 2.0.5 on 2018-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoarticulo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fotoespacio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
