# Generated by Django 2.0.5 on 2018-05-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0002_auto_20180508_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
