# Generated by Django 2.0.5 on 2018-06-30 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0002_auto_20180630_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaarticulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reservaespacio',
            name='estado',
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 24, 43, 940242)),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 24, 43, 940738)),
        ),
    ]
