# Generated by Django 2.0.5 on 2018-05-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0003_espacio_capacidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoarticulo',
            old_name='id_articulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='fotoarticulo',
            old_name='foto',
            new_name='ruta',
        ),
        migrations.RenameField(
            model_name='fotoespacio',
            old_name='id_espacio',
            new_name='espacio',
        ),
        migrations.RenameField(
            model_name='fotoespacio',
            old_name='foto',
            new_name='ruta',
        ),
        migrations.RenameField(
            model_name='reservaarticulo',
            old_name='id_articulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='reservaespacio',
            old_name='id_espacio',
            new_name='espacio',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
