# Generated by Django 2.0.5 on 2018-06-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0003_auto_20180630_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaarticulo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 25, 28, 511697)),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 25, 28, 512205)),
        ),
    ]
