# Generated by Django 2.0.5 on 2018-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0004_auto_20180509_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoarticulo',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='fotoespacio',
            name='espacio',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Perdido'), (1, 'Disponible'), (2, 'En Préstamo'), (3, 'Perdido o Inutilizable')], default=1),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Perdido'), (1, 'Disponible'), (2, 'En Préstamo'), (3, 'Perdido o Inutilizable')], default=1),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_inicial',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Rechazada'), (1, 'Aprobada'), (2, 'Pendiente')], default=2),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_inicial',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='FotoArticulo',
        ),
        migrations.DeleteModel(
            name='FotoEspacio',
        ),
    ]
