# Generated by Django 2.0.5 on 2018-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0005_auto_20180517_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='espacio',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
