# Generated by Django 2.0.5 on 2018-06-30 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0005_auto_20180630_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 27, 51, 194549)),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 27, 51, 195059)),
        ),
    ]
