# Generated by Django 2.0.5 on 2018-05-17 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0006_auto_20180517_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEspacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='foto',
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='hora_final',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='hora_inicial',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(9)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='hora_final',
            field=models.IntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='hora_inicial',
            field=models.IntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(9)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_inicial',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='fotoespacio',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Espacio'),
        ),
        migrations.AddField(
            model_name='fotoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasApp.Articulo'),
        ),
    ]
