# Generated by Django 2.0.5 on 2018-06-30 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0009_auto_20180630_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaarticulo',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 23, 35, 7, 415335)),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 23, 35, 7, 415839)),
        ),
    ]
